# Generated by Django 5.2.1 on 2025-05-17 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctorcategory',
            options={'verbose_name': 'Doctor Category', 'verbose_name_plural': 'Doctor Categories'},
        ),
        migrations.AlterModelOptions(
            name='doctorspecialization',
            options={'verbose_name': 'Doctor Specialization', 'verbose_name_plural': 'Doctor Specializations'},
        ),
    ]
