# Generated by Django 5.2.1 on 2025-05-18 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_doctorcategory_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='full_name',
        ),
        migrations.AddField(
            model_name='myuser',
            name='patronymic',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество'),
        ),
    ]
