# Generated by Django 5.2.1 on 2025-05-19 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_client_full_name_remove_doctor_full_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorcategory',
            name='description',
        ),
    ]
