# Generated by Django 5.2.1 on 2025-05-17 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.client'),
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='main.category'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='employee_position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.employeeposition'),
        ),
    ]
