# Generated by Django 5.2.1 on 2025-05-17 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='employee_position',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='doctor_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.doctorcategory'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='doctor_specialization',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='users.doctorspecialization'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='EmployeePosition',
        ),
    ]
