# Generated by Django 5.2.1 on 2025-05-18 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_vacancy_employee_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companystory',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='main.company'),
            preserve_default=False,
        ),
    ]
