# Generated by Django 5.2.1 on 2025-05-20 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_review_rate'),
        ('users', '0004_remove_doctorcategory_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorAvailableTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_times', to='users.doctor')),
            ],
            options={
                'ordering': ['start_time'],
                'unique_together': {('doctor', 'start_time')},
            },
        ),
    ]
