# Generated by Django 5.2.1 on 2025-05-20 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_appointment'),
        ('users', '0004_remove_doctorcategory_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DoctorAvailableTime',
            new_name='DoctorSchedule',
        ),
    ]
